# Generated by Django 4.2.10 on 2024-05-20 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='task.project'),
            preserve_default=False,
        ),
    ]
